version: '3.1'

services:

    db:
      ports:
        - 5432:5432
      image: postgres
      environment:
        POSTGRES_DB: shoppingcart3
        POSTGRES_USER: jacobono
        POSTGRES_PASSWORD: ''
